name: blue_thermal_printer
description: A Flutter plugin for connecting to thermal printer via bluetooth
version: 1.2.4
homepage: https://kakzaki.dev
repository: https://github.com/kakzaki/blue_thermal_printer
issue_tracker: https://github.com/kakzaki/blue_thermal_printer/issues
documentation: https://github.com/kakzaki/blue_thermal_printer/blob/master/README.md

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: kg.zkdev.blue_thermal_printer
        pluginClass: BlueThermalPrinterPlugin
      ios:
        pluginClass: BlueThermalPrinterPlugin
      macos:
        pluginClass: BlueThermalPrinterPlugin
